<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produk;
use Carbon\Carbon;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Menggunakan insert agar lebih efisien untuk banyak data, 
        // pastikan tidak ada data duplikat jika menjalankan ulang tanpa migrate:fresh
        Produk::insert([
            [
                'id_produk' => 'PROD001',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Jasmine Tea',
                'deskripsi' => 'Teh Melati dengan aroma bunga yang menyenangkan dan rasa teh yang lembut di lidah. Cocok dinikmati saat ingin relaks, memberi ketenangan dalam setiap tegukan dan bikin pikiran adem kayak pagi di pegunungan.',
                'gambar_produk' => 'produk/TS-jasmine.png',
                'harga' => 2500.00,
                'jumlah_terjual' => 12000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD002',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Markisa Tea',
                'deskripsi' => 'Teh markisa yang eksotis dengan rasa asam-manis yang khas, pas banget buat kamu yang suka rasa tropical yang beda. Setiap seruputannya bikin seger, cocok buat penghilang penat di tengah kesibukan.',
                'gambar_produk' => 'produk/TS-markisa.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 750,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD003',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Tea Tarik',
                'deskripsi' => 'Kombinasi teh hitam pekat dan susu creamy ala mamak-mamak Malaysia, disajikan dengan manis pas dan buih lembut di atasnya. Rasanya kaya dan memuaskan, sempurna untuk pencinta teh manis nan creamy.',
                'gambar_produk' => 'produk/TS-teaTarik.png',
                'harga' => 7000.00,
                'jumlah_terjual' => 10000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD004',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Lychee Tea',
                'deskripsi' => 'Kombinasi lembut antara teh pilihan dan rasa leci yang elegan. Memberikan pengalaman minum teh yang manis, harum, dan classy. Pas banget buat kamu yang suka vibe calm tapi tetap fancy.',
                'gambar_produk' => 'produk/TS-lychee.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD005',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Lemon Tea',
                'deskripsi' => 'Perpaduan rasa asam segar dari lemon dengan teh pilihan menciptakan minuman yang menyegarkan dan bikin melek. Cocok banget buat nemenin siang panas atau recharge energi setelah aktivitas padat.',
                'gambar_produk' => 'produk/TS-lemon.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 860,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD006',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Mango Tea',
                'deskripsi' => 'Manis segarnya mangga tropis dipadukan dengan teh yang ringan menjadikan minuman ini favorit semua kalangan. Aromanya wangi, rasanya menyenangkan, cocok dinikmati kapan pun dan di mana pun.',
                'gambar_produk' => 'produk/TS-mango.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 780,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD007',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Grape Tea',
                'deskripsi' => 'Teh dengan cita rasa anggur manis dan aroma buah yang menggoda. Cocok buat kamu yang suka rasa unik tapi tetap ringan. Manisnya pas, segarnya dapet, bikin gak cukup cuma satu gelas!',
                'gambar_produk' => 'produk/TS-grape.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 390,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD008',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Melon Tea',
                'deskripsi' => 'Teh dengan rasa melon yang manis, segar, dan aromatik. Cocok banget buat teman ngemil atau nugas. Rasanya ringan tapi ngena, kayak senyuman gebetan — bikin nagih terus!',
                'gambar_produk' => 'produk/TS-melon.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 400,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD009',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Strawberry Tea',
                'deskripsi' => 'Rasakan manis dan sedikit asam dari buah stroberi segar yang menyatu sempurna dengan teh yang menenangkan. Ideal untuk kamu yang suka minuman dengan karakter ceria dan menyegarkan.',
                'gambar_produk' => 'produk/TS-strawberry.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 570,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD010',
                'id_kategori' => 'KAT001',
                'nama_produk' => 'Apple Tea',
                'deskripsi' => 'Teh apel yang menyegarkan dengan aroma khas buah apel segar, memberikan sensasi ringan dan natural. Cocok untuk kamu yang suka rasa fruity tapi tetap kalem, pas buat nemenin hari santaimu.',
                'gambar_produk' => 'produk/TS-apple.png',
                'harga' => 5000.00,
                'jumlah_terjual' => 4500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD011',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Choco Oreo Creamy',
                'deskripsi' => 'Perpaduan cokelat creamy dan remahan Oreo renyah yang meleleh di mulut. Milky vibes-nya dapet banget, bikin tiap tegukan serasa ngemil cokelat sambil ngopi santai di café hits!',
                'gambar_produk' => 'produk/MS-chocoOreo.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD012',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Royal Choco Creamy',
                'deskripsi' => 'Cokelat premium dengan rasa rich dan tekstur creamy yang memanjakan lidah. Minuman ini diciptakan buat choco lovers sejati yang gak main-main soal kenikmatan. Royal taste in every sip!',
                'gambar_produk' => 'produk/MS-royalChoco.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 4900,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD013',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Cocho Caramel Creamy',
                'deskripsi' => 'Cokelat manis yang lembut disiram dengan rasa caramel gurih, menciptakan perpaduan yang super indulgent. Kayak minum pelukan hangat—comforting dan bikin jatuh cinta dari seruput pertama.',
                'gambar_produk' => 'produk/MS-chocoCaramel.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 640,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD014',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Silverqueen Creamy',
                'deskripsi' => 'Gabungan susu milky dan potongan cokelat SilverQueen yang legit dan lumer. Sensasi nyoklat yang crunchy dan lembut sekaligus minuman + cemilan dalam satu gelas!',
                'gambar_produk' => 'produk/MS-silverQueen.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 460,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD015',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Bubble Gum Creamy',
                'deskripsi' => 'Minuman dengan rasa permen karet khas yang playful dan nostalgic. Manis, wangi, dan bikin mood auto good! Cocok buat kamu yang fun, ceria, dan nggak suka yang biasa-biasa aja.',
                'gambar_produk' => 'produk/MS-bubbleGum.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD016',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Blackcurrant Creamy',
                'deskripsi' => 'Rasa unik dari buah blackcurrant yang manis-asam, berpadu dengan susu creamy bikin minuman ini standout banget. Segar tapi tetap lembut — cocok buat yang suka eksplor rasa beda.',
                'gambar_produk' => 'produk/MS-blackcurrant.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 700,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD017',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Avocado Creamy',
                'deskripsi' => 'Rasa alpukat creamy yang khas berpadu dengan susu manis yang halus. Kaya rasa, lembut di lidah, dan pastinya bikin kenyang plus senang! Cocok buat kamu yang suka rasa klasik tapi tetap spesial.',
                'gambar_produk' => 'produk/MS-avocado.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 1200,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD018',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Matcha Creamy',
                'deskripsi' => 'Matcha otentik dari Jepang yang earthy dan sedikit pahit, berpadu manis dengan susu kental nan lembut. Cocok buat kamu pecinta matcha sejati yang suka rasa calm tapi dalam.',
                'gambar_produk' => 'produk/MS-chocoOreo.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 980,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD019',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Red Velvet Creamy',
                'deskripsi' => 'Perpaduan elegan antara susu dan rasa red velvet yang lembut, manis, dan berkelas. Warnanya cantik, rasanya pun mewah. Tiap seruput bikin kamu ngerasa fancy — like a royal!',
                'gambar_produk' => 'produk/MS-redVelvet.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 670,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD020',
                'id_kategori' => 'KAT002',
                'nama_produk' => 'Taro Creamy',
                'deskripsi' => 'Rasa talas khas taro yang manis dan wangi banget, dikombinasi dengan susu lembut yang creamy. Warnanya ungu, rasanya dreamy — mood booster banget buat hari kamu yang sibuk!',
                'gambar_produk' => 'produk/MS-taro.png',
                'harga' => 10000.00,
                'jumlah_terjual' => 550,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD021',
                'id_kategori' => 'KAT003',
                'nama_produk' => 'Strawberry Squash',
                'deskripsi' => 'Rasakan cinta pada sedotan pertama! Strawberry Squash ini punya rasa manis alami buah stroberi yang segar dan bikin mood naik drastis. Warnanya cantik, rasanya romantis. Cocok banget buat yang pengen chill atau pengen manis-manis.',
                'gambar_produk' => 'produk/SS-strawberry.png',
                'harga' => 8000.00,
                'jumlah_terjual' => 1200,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD022',
                'id_kategori' => 'KAT003',
                'nama_produk' => 'Lychee Squash',
                'deskripsi' => 'Eksotis dan lembut, Lychee Squash hadir buat kamu yang pengen rasa unik nan elegan. Dingin-dingin minum ini? Fix, langsung adem hati. Kombinasi rasa manis dan aroma khas leci-nya bikin tiap tegukan nggak bisa berhenti.',
                'gambar_produk' => 'produk/SS-lychee.png',
                'harga' => 8000.00,
                'jumlah_terjual' => 480,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD023',
                'id_kategori' => 'KAT003',
                'nama_produk' => 'Orange Squash',
                'deskripsi' => 'Segarnya jeruk pilihan langsung menyapa lidahmu! Orange Squash ini dibuat dari ekstrak jeruk berkualitas dengan rasa manis-asam yang bikin nagih. Cocok banget diminum pas siang hari atau nemenin kerjaan. Vitamin C-nya nendang, segarnya maksimal!',
                'gambar_produk' => 'produk/SS-orange.png',
                'harga' => 8000.00,
                'jumlah_terjual' => 980,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD024',
                'id_kategori' => 'KAT003',
                'nama_produk' => 'Grape Squash',
                'deskripsi' => 'Anggur ungu yang juicy banget, diblender dengan cita rasa asam-manis yang pas di lidah. Grape Squash ini adalah minuman para sultan wannabe—elegan, mewah, dan bikin nagih! Sekali coba',
                'gambar_produk' => 'produk/SS-grape.png',
                'harga' => 8000.00,
                'jumlah_terjual' => 400,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD025',
                'id_kategori' => 'KAT004',
                'nama_produk' => 'Thai Tea Original',
                'deskripsi' => 'Rasakan sensasi segarnya teh hitam berpadu dengan creamy-nya susu kental manis yang bikin nagih. Cocok banget buat yang cari rasa klasik yang gak pernah salah.',
                'gambar_produk' => 'produk/TT-original.png',
                'harga' => 6000.00,
                'jumlah_terjual' => 9500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD026',
                'id_kategori' => 'KAT004',
                'nama_produk' => 'Thai Tea Machiato',
                'deskripsi' => 'Teh Thailand creamy dengan topping foam macchiato yang lembut dan gurih. Rasanya balance antara manis dan sedikit asin, cocok buat kamu yang suka minuman dengan depth rasa.',
                'gambar_produk' => 'produk/TT-macchiato.png',
                'harga' => 8000.00,
                'jumlah_terjual' => 3000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD027',
                'id_kategori' => 'KAT004',
                'nama_produk' => 'Thai Tea Oreo',
                'deskripsi' => 'Thai tea yang creamy dipaduin sama taburan Oreo crunchy di setiap tegukan. Bikin tiap seruput berasa dapet bonus ngemil!',
                'gambar_produk' => 'produk/TT-oreo.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD028',
                'id_kategori' => 'KAT004',
                'nama_produk' => 'Thai Tea Choco',
                'deskripsi' => 'Perpaduan antara teh Thailand yang khas dan cokelat premium menciptakan rasa baru yang kaya, manis, dan super comforting.',
                'gambar_produk' => 'produk/TT-choco.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 8500,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD029',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Strawberry',
                'deskripsi' => 'Perpaduan rasa manis-asam stroberi segar dengan Yakult yang khas. Rasanya ringan, nyegerin, dan bikin suasana hati auto cerah. Cocok banget buat nemenin hari sibuk kamu!',
                'gambar_produk' => 'produk/YS-strawberry.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 1200,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD030',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Grape',
                'deskripsi' => 'Yakult dengan sentuhan rasa anggur manis yang khas. Rasanya unik, sedikit asam tapi tetap smooth. Cocok buat kamu yang pengen minuman beda dari yang lain tapi tetap fun!',
                'gambar_produk' => 'produk/YS-grape.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 980,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD031',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Mango',
                'deskripsi' => 'Yakult berpadu dengan mangga tropis yang juicy dan manis alami. Minuman ini punya rasa yang seimbang antara segar, creamy, dan fruity. Gak cuma enak, tapi juga bikin fresh!',
                'gambar_produk' => 'produk/YS-mango.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 860,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD032',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Lychee',
                'deskripsi' => 'Yakult leci yang manis dan aromatik, memberikan sensasi menyegarkan yang classy. Tiap tegukan rasanya elegan tapi tetap playful — pas banget buat siang hari yang panas!',
                'gambar_produk' => 'produk/YS-lychee.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 930,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD033',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Orange',
                'deskripsi' => 'Yakult jeruk dengan rasa citrus yang segar dan sedikit asam — bikin mata melek dan mulut senang. Sensasi Yakult-nya bikin badan seger dan perut adem, cocok diminum kapan aja!',
                'gambar_produk' => 'produk/YS-orange.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 950,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_produk' => 'PROD034',
                'id_kategori' => 'KAT005',
                'nama_produk' => 'Yakult Melon',
                'deskripsi' => 'Melon segar bertemu Yakult dalam satu cup yang penuh kesegaran. Manis, creamy, dan sejuk di tenggorokan. Minuman andalan buat ngilangin penat dan boost semangatmu!',
                'gambar_produk' => 'produk/YS-melon.png',
                'harga' => 9000.00,
                'jumlah_terjual' => 320,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}